 
name: relay_server
description: "Relay WebSocket server for Scrabble_P2P"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.0
  shelf_web_socket: ^1.0.1
  collection: ^1.17.0
  postgres: ^2.6.3
  
startCommand: dart run lib/relay_server.dart